### ISSUE TITLE
Cannot enter bootloader mode

### ISSUE THREAD

**Issue by nguyenhimself** [hsgw/plaid#11]
I had my Plaid working for a month. Now I want to flash a new layout.
I understand that to enter bootloader mode, I have to:

1. Plug into USB cable
2. Push and hold RESET SW
3. Push and hold BOOT SW
4. Release RESET SW
5. Release BOOT SW

However, when I pushed the BOOT button, it just output "edc", i.e the keys on the 4th column, so now I cannot enter bootloader mode to flash my new layout.
Again, aside from the BOOT button, all the other keys of my Plaid still works fine.
How should I go about solving this? Thanks.

**Comment by Chemistt** [comment]
check if your RESET button works, it will disconnect and reconnect the board.
Will return "edc" if switch button is not pushed down while pressing the BOOT button as BOOT switch is using the same pin as COL3 (See schematics).

**Comment by miguelangelramirez** [comment]
Cool, just ordered a new atmega chip with a pre-loaded bootloader on it. Will check on this method when I finally get it. Thanks!

> check if your RESET button works, it will disconnect and reconnect the board.
> Will return "edc" if switch button is not pushed down while pressing the BOOT button as BOOT switch is using the same pin as COL3 (See schematics).
