### ISSUE TITLE
Support for a rotary encoder

### ISSUE THREAD

**Issue by To1ne** [hsgw/plaid#12]
I'm curious what it would take to add a rotary encoder to the Plaid?

Some related links:
- https://www.reddit.com/r/MechanicalKeyboards/comments/brnl0q/a_companion_for_my_planck/
- https://www.reddit.com/r/olkb/comments/9jzbg1/help_with_rotary_encoder_code/

**Comment by hsgw** [comment]
Hi, I wouldn't like to add support rotary encoder on pcb.
But you can use i2c pins.
