### ISSUE TITLE
Led series resistor value

### ISSUE THREAD

**Issue by BenRoe** [hsgw/plaid#14]
Hi,
a 1.5k series resistor (R7, R8) for the led's seems a bit high. My led glow so low, that it's not visible during the date.
Is a value 470Ω, or even less not better?
How much is the signal from the Atmega328P 3V or 5V?
If i [calculate](https://www.hobby-hour.com/electronics/ledcalc.php) the series resistor for a red led, it suggest's a 150Ω resistor.

**Comment by hsgw** [comment]
Atmega328p run at 5V.

I think my leds is bright enough.

If they are changed to 470R or 150R, LEDs are brighter and shouldn't be broken.

**Comment by BenRoe** [comment]
First i bought led's with 60-100mcd and they were so low that you can't see them at daylight.
Then i bought some with 600-800mcd and they have a good glow.
Maybe it's worth to mention in the BOM.
