### ISSUE TITLE
Resistor slots are too short for 10k and 1.5k resistors

### ISSUE THREAD

**Issue by themoonisacheese** [hsgw/plaid#2]
the slots for R1,4,6,7 are shorter than the standard size for these resistors.
I was able to mount them anyway by bending the leg under each resistor to match the hole, but please consider allocating more space, especially considering all of these resistors have (visually, I don't know if there is a trace there) enough space next to them.

**Comment by hsgw** [comment]
All resistors are 1/8W and fit without issues.
