### ISSUE TITLE
Should I have nuts?

### ISSUE THREAD

**Issue by CrisHale** [hsgw/plaid#25]
But seriously, I have the Plaid Gold kit and I've got two differently sized spacers, 5 mm and 8 mm, but the guide says you should have nuts that connect the back plate. Does that mean I'm missing something? I only have 10 5 mm spacers, which is not enough to secure all the screws.

**Comment by BenRoe** [comment]
@CrisHale please asked plaid gold related questions at the keycapsss discord server or via mail.
So we don't bother hsgw with this question.

**Comment by CrisHale** [comment]
@BenRoe I think I've figured it out - the small screws could go on the bottom, but thanks.
