### ISSUE TITLE
Gerber files for main pcb, switch plate, bottom plate

### ISSUE THREAD

**Issue by synwt** [hsgw/plaid#39]
Where can I find it?

**Comment by hsgw** [comment]
here
https://github.com/hsgw/plaid/tree/master/pcb

**Comment by synwt** [comment]
Hi @hsgw and all developer of Plaid,

My capability is not in electronics. I just want to print and use your pcb for independent-use according to your original concept, namely through-hole with vusb.

So, would you mind making a gerber file (main pcb, switch plate pcb, and bottom pcb), so that ordinary people can use your ready-to-print master gerber file?

**Comment by hsgw** [comment]
Different factories producing PCBs may require different Gerber data. I cannot guarantee that, so I do not distribute that directly.

And there are many helpful instruciton available, so download kicad and try it for yourself.
